"""initial_schema

Revision ID: 8935d6b9dd7b
Revises: 
Create Date: 2026-10-03 08:36:50.268754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8935d6b9dd7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('P0', 'P1', 'P2', 'P3', 'P4', name='incidentseverity'), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'ACKNOWLEDGED', 'INVESTIGATING', 'PROPOSED', 'EXECUTING', 'RESOLVED', 'FAILED', 'ESCALATED', name='incidentstatus'), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('source_service', sa.String(length=255), nullable=True),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('remediation_plan', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('graph_state', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('current_agent_node', sa.String(length=100), nullable=True),
    sa.Column('time_to_detect', sa.Float(), nullable=True),
    sa.Column('time_to_resolve', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SRE', 'LEAD', 'DEVELOPER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('slack_user_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_handle', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('PAGERDUTY', 'SENTRY', 'DATADOG', 'CLOUDWATCH', 'PROMETHEUS', 'GENERIC', name='alertsource'), nullable=False),
    sa.Column('source_alert_id', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('sanitized_payload', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_source'), ['source'], unique=False)

    op.create_table('runbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_args', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'EXECUTING', 'EXECUTED', 'FAILED', 'REJECTED', 'EXPIRED', 'ROLLED_BACK', name='invocationstatus'), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('execution_result', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('health_check_passed', sa.Boolean(), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approval_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_invocations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_invocations_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_invocations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_invocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_invocations_status'))
        batch_op.drop_index(batch_op.f('ix_tool_invocations_risk_level'))
        batch_op.drop_index(batch_op.f('ix_tool_invocations_incident_id'))

    op.drop_table('tool_invocations')
    op.drop_table('runbooks')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_source'))
        batch_op.drop_index(batch_op.f('ix_alerts_ingested_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_fingerprint'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_incidents_created_at'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
